# Generated by Django 3.0 on 2020-01-30 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_no', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Salon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('branch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='darjano.Branch')),
            ],
        ),
    ]
