# Generated by Django 3.0 on 2020-02-02 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('darjano', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='slug',
            field=models.SlugField(default='SLUG', unique=True),
        ),
    ]
