# Generated by Django 3.0 on 2020-02-02 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('darjano', '0002_salon_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salon',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
