# Generated by Django 3.0 on 2020-02-02 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('darjano', '0003_auto_20200202_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salon',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
